title: Imagine Wu
author: Imagine Wu
email: icosseeker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to Imagine Wu.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ImagineWu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
